### ISSUE TITLE
サイトの名前を決める

### ISSUE THREAD

**Issue by MayumiKamio** [MayumiKamio/edubase#1]

**Comment by MayumiKamio** [comment]
サイト名のアイディアメモ

現状：
教員・教育委員会のオンライン学習支援事例まとめサイト

キーワード：
挑戦、試行錯誤、教員、オンライン学習、クリエイティブ、実験、ラボ、研究、データベース、ベース(基地)、先生、実践事例、EdTech、EduBASE、学び合い、

データベースと基地の意味のBASEをかけて、edbaseとかはどうか？


例）
**サイト名：edbase
サブタイトル：教員・教育委員会のオンライン学習支援事例まとめサイト**

**Comment by ayazawa** [comment]
・みんなの教室
・もう１つの教室
・あたらしい教室

**Comment by MayumiKamio** [comment]
Ver1 確定

『オンライン授業lab』
オンラインで学びの場をアップデートする教員・教育委員会のための情報サイト

「新しい教室の在り方の1つにオンラインの空間という選択肢が増えました。
　これまでの学校での取り組みの何がアップデートされていくといいのかみんなで
　試行錯誤していきませんか。みんなの挑戦レポートを共有しますので、
　あなたの学校、授業のアップデートのヒントにしてください」

ーUPDATE「教室」
ーUPDATE「休み時間」
ーUPDATE「HR」
ーUPDATE「理科実験」
