### ISSUE TITLE
ドメインを決めて取得する

### ISSUE THREAD

**Issue by MayumiKamio** [MayumiKamio/edubase#11]

**Comment by MayumiKamio** [comment]
@MutsuOno @Keyhoh @ayazawa 
ドメイン 、シンプルに以下いずれかはどうかなーと思いますが、いかがでしょうか。

①　classtech-lab.com 
②　classtechlab.com

**Comment by Keyhoh** [comment]
@MayumiKamio 
個人的に①ですー

**Comment by MayumiKamio** [comment]
@Keyhoh ありがとうございます！

@MutsuOno @ayazawa 
いかがでしょうか〜？

**Comment by ayazawa** [comment]
@MayumiKamio 遅くなってしまい申し訳ございません。
私も①でいいと思います！

**Comment by MayumiKamio** [comment]
@ayazawa  サンキュー！
