### ISSUE TITLE
スプレッドシートのフォーマットをそろえる

### ISSUE THREAD

**Issue by Keyhoh** [MayumiKamio/edubase#13]
- カンマが全半角混在しているので半角カンマに統一する（例：「国語，数学」->「国語,数学」）
- 入力なしの項目が空セルだったり「－」になっているのを統一する（例：「－」->「」）

例はあくまでも例なので、実際のフォーマットはgoogle formとの連携を考慮して決定する。

**Comment by ayazawa** [comment]
データベースの記入手引きを作成したので共有します。確認お願いします。
@MayumiKamio
